language: java
before_install:
  - cd ..
  - git clone git://github.com/jgralab/common.git
  - cd common
  - ant
  - cd ../jgralab
install: ant
script: ant test
jdk:
  - oraclejdk7
#  - openjdk7
#  - oraclejdk6
#  - openjdk6
